cask_args appdir: '/Applications'

tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "cmake"
brew "go"
brew "mono", link: false
brew "python"
brew "tmux"
brew "tree"
brew "zsh"

cask "adobe-acrobat-reader"
cask "cyberduck"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-hack-nerd-font"
cask "gimp"
cask "google-chrome"
cask "iterm2"
cask "jetbrains-toolbox"
cask "mono-mdk"
cask "spotify"
cask "visual-studio"
cask "visual-studio-code"
cask "vlc"
